### ISSUE TITLE
Issues needed to be solved before production

### ISSUE THREAD

**Issue by JanezCim** [UbiquityRobotics/magni_robot#191]
- [x] Make sure Top plate with lidar mounts is in the standard magni 3D files - include those files into what is sent to pečnik #184 
- [x] Fix up standard work till the end (especially packaging instructions) https://github.com/UbiquityRobotics/magni_robot/issues/192
- [ ] ~Upate cerificate of conformoty [#certhttps://github.com/UbiquityRobotics/ubiquity_main/issues/255](https://github.com/UbiquityRobotics/ubiquity_main/issues/255)~ (being tracked in another issue)
